[project]
name = "book-recommendation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.0.3",
    "numpy>=2.1.1",
    "pandas>=2.2.3",
]
